### ISSUE TITLE
Add case study content

### ISSUE THREAD

**Issue by bkingbking** [getroadmap/roadmap-site#11]
We received an email from Peggy Goodfriend (pgoodfriend@ketc.org) about the link being broken.  

> Good morning – the link to the demo seems to redirect to the wrong place, just FYI.

![screen shot 2014-10-16 at 11 01 57 am](https://cloud.githubusercontent.com/assets/2389362/4664635/67338852-5545-11e4-888e-100cd50d3eb2.png)

Here's the link to the [entire video on Vimeo](https://vimeo.com/89462575).  Ideally, we break-up the content in a similar fashion as the old page (which used links pointing to specific time stamps).

**Comment by benkutil** [comment]
@bkingbking could you reach out to Jerry at Blvr and see if he had any other photos like this:

![Blvr approach image](http://blvr.com/wp-content/uploads/2014/08/about_approach.jpg)

Or if we could use this image on the case study?

**Comment by bkingbking** [comment]
@benkutil Sure.  Is this image from their site?  Also, we'll need to modify some of the content to reflect the fact that they've rebranded since the profile.

**Comment by benkutil** [comment]
Yeah, this was from their new site.

Jerry's got a nice profile shot, but wonder if he's in a situational one like the example.

**Comment by bkingbking** [comment]
I've put a message to Jerry . .  .

**Comment by bkingbking** [comment]
@benkutil Jerry wrote:
 > The new stuff your team is working on looks rad! No problem on using the group photo from our Approach page. We don't have a ton of professional grade photos with the entire staff in them, however, here area  couple of links to our social media pages that may have some stuff you can use. If you see anything you like and need a higher res version, just send me a link to the image and I'll track down the hi-rez version for you. Take care my friend :)
https://twitter.com/goBLVR
https://www.facebook.com/goBLVR
