### ISSUE TITLE
Public site Pricing missing "unlimited users" for Plus and Pro

### ISSUE THREAD

**Issue by bkingbking** [getroadmap/roadmap-site#17]
[Pricing](https://ppmroadmap.com/plans-pricing/index.html) is missing references to unlimited users on Plus and Pro.

#### Account page in app

![screen shot 2015-02-02 at 12 37 01 pm](https://cloud.githubusercontent.com/assets/2389362/6005465/86bb9a0a-aad8-11e4-8565-62a3a5f46f69.png)

#### Public site (current)

![screen shot 2015-02-02 at 12 39 33 pm](https://cloud.githubusercontent.com/assets/2389362/6005478/9e742f40-aad8-11e4-9ff0-7efce55d6746.png)

**Comment by benkutil** [comment]
@bkingbking, it’s not. I don't like sites that have really long comparison tables.

I’ll change some of the bolding on the comparison table so that it is more apparent, but I don't think it is necessary.

**Comment by benkutil** [comment]
Making content more clear through #18
