### ISSUE TITLE
Release Notes - March 28, 2015

### ISSUE THREAD

**Issue by bkingbking** [getroadmap/roadmap-site#22]
#### Goals
* More reporting flexibility: multiple views on all grid tabs, pivot tables, and column-level filters
* Increased reporting precision: reporting timeframes (custom date ranges), and one work item = one row (Work Items Tab)
* New data types or reports: resource attributes, and new columns
* Better capacity planning: utilization chart
* Easier view management: adjust column width, and drag-and-drop column location

We created the Work Items Tab to provide a cross-portfolio view of anything that can be assigned to a resource, and where each assignment gets it's own row in the grid.  Trying to cram everything -- projects, resources, and work items -- into a single view, in this case the Projects Tab, dilutes the value everything.

What this means is that instead of viewing individual milestones, to-dos, roadblocks, etc in their complete form on the Projects Tab, we introduced the concept of "counts" columns.  For example, if a project has 25 incomplete to-dos, the **To-Do Count** column will display **25** in the cell.  Clicking on the value (25) will create an on-the-fly Work Items Tab view in a new browser window.  Thus, you view the details of those 25 incomplete to-dos in the context of the tab (Work Items Tab) that is designed for that purpose.

We apologize for any inconvenience these changes may have caused, but we also believe the value and usefulness of the Work Items Tab will more than offset any inconvenience.

#### Projects Tab

* Pivot tables, column-level filters, reporting timeframe
* Ability to save your all of your preferences, including column widths, column filters, reporting timeframe, etc
* Schedule Audit is broken up into multiple columns
* New columns:
 * Date Closed
 * Planned vs. Actual vs. Difference (time)
 * Planned vs. Actual vs. Difference (currency)

#### Work Items Tab (new)

* In addition to the reporting and view management features as the Project Tab . . . 
* Each work item has a dedicated row.  Important: Add **Type** column to your view so you can filter by to-do, milestone, roadblock, project (overall project level forecasting assignment), and event
* Use column filters to include completed work items (plus the completed date)
* Cross-over columns: 
 * OOTB project attributes and custom project attributes
 * OOTB resource attributes and custom resource attributes

Jump to [Work Items Tab](https://app.ppmroadmap.com/WorkItems.aspx)

#### Resources Tab

* In addition to the reporting and view management features as the Project Tab . . . 
* Ability to create new views that are separate from administrative functions like schedule, privileges, last login, etc
* Utilization Chart supports individual or groups of resources or roles.  Toggle between hours or %, and apply built-in or custom reporting timeframes.
* New columns:
 * Email
 * Milestone Count
 * Planned (time)
 * Planned (currency)
 * Planned vs. Actual vs. Difference (time)
 * Planned vs. Actual vs. Difference (currency)
 * Project Count
 * Roadblock Count
 * To-Do Count
 * Work Item Count
 * Custom resource attributes

#### Time Tab

* In addition to the reporting and view management features as the Project Tab . . . 
* Description column is broken out into multiple columns to provide greater flexibility and precision
* New columns:
 * Time Entry Source
* Cross-over columns: 
 * OOTB project attributes and custom project attributes
 * OOTB work items attributes
 * Custom resource attributes

#### Resource Attributes

* Create custom criteria to characterize resources (think skill, office, language, certifications, employment status)
* Use resource attributes to further narrow available resources when using **Find by Availability** on Project 360 pages

Jump to [Resource Attributes](https://app.ppmroadmap.com/ResourcePreferences.aspx) management page

#### Dashboard Tab

Resource availability and utilization widgets logic modified to include assignments where only role is specified (makes it behave the same as the new Utilization Chart).

**Comment by benkutil** [comment]
A post linking to this information is now available on the [homepage ](http://getroadmap.github.io/roadmap-site/), in the [News](http://getroadmap.github.io/roadmap-site/updates/) section, and their is a link in the footer for Release Notes, which will [go to the most recent release notes on UV](https://ppmroadmap.uservoice.com/knowledgebase/articles/529159-release-notes-march-28-2015). That link will be manually updated.
